/**
 * Copyright (c) 2011 Nokia Corporation.
 */

var DEFAULT_MARGIN = 10;
var DEFAULT_BUTTON_WIDTH = 100;
var DEFAULT_BUTTON_HEIGHT = 40;
var DEFAULT_HEADER_HEIGHT = 80;
var HEADER_BUTTON_WIDTH = 64;
var HEADER_BUTTON_HEIGHT = 64;
var LIST_ITEM_DEFAULT_HEIGHT = 70;
var LIST_ITEM_DEFAULT_HEIGHT_E6 = 80;
var PROGRESSBAR_BASE_HEIGHT = 5;
var PROGRESSBAR_HEIGHT = 14;
var DEFAULT_ANIM_DURATION = 200;
var SWITCH_PAGE_ANIM_DURATION = 300;
var SPLASHSCREEN_FONT_POINTSIZE = 40;
var PROGRESSBAR_STEP_INTERVAL = 200;
var PROGRESSBAR_VALUE_STEP = 20;
var PROGRESSBAR_MAX_VALUE = 100;
var DARK_ACCENT_COLOR = "#222222";
var BORDER_COLOR = "#404040";

var ContentType = { Images: 0,
                    Sounds: 1,
                    Videos: 2 };

// End of file.
